# Generated by Django 6.0.1 on 2026-01-19 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('SPPU', 'SPPU'), ('PBAS', 'PBAS')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('appraisal_data', models.JSONField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('HOD_APPROVED', 'HOD Approved'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('LOCKED', 'Locked')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'appraisals',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.TextField()),
                ('role', models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('PRINCIPAL', 'Principal')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AppraisalScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('teaching_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('research_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('activity_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('feedback_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appraisal', models.OneToOneField(db_column='appraisal_id', on_delete=django.db.models.deletion.CASCADE, to='core.appraisal')),
            ],
            options={
                'db_table': 'appraisal_scores',
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'faculty_profiles',
            },
        ),
        migrations.AddField(
            model_name='appraisal',
            name='faculty',
            field=models.ForeignKey(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, to='core.facultyprofile'),
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('pdf_id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_path', models.TextField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appraisal', models.ForeignKey(db_column='appraisal_id', on_delete=django.db.models.deletion.CASCADE, to='core.appraisal')),
            ],
            options={
                'db_table': 'generated_pdfs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('entity', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='appraisal',
            unique_together={('faculty', 'academic_year', 'semester', 'form_type')},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('file_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appraisal', models.ForeignKey(db_column='appraisal_id', on_delete=django.db.models.deletion.CASCADE, to='core.appraisal')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'db_table': 'documents',
                'unique_together': {('appraisal', 'document_type', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('HOD', 'HOD'), ('PRINCIPAL', 'Principal')], max_length=20)),
                ('action', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT_BACK', 'Sent Back')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appraisal', models.ForeignKey(db_column='appraisal_id', on_delete=django.db.models.deletion.CASCADE, to='core.appraisal')),
                ('approved_by', models.ForeignKey(db_column='approved_by', on_delete=django.db.models.deletion.PROTECT, to='core.user')),
            ],
            options={
                'db_table': 'approval_history',
                'unique_together': {('appraisal', 'role')},
            },
        ),
    ]
