# Generated by Django 6.0.1 on 2026-01-20 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_appraisals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('RETURNED_BY_HOD', 'Returned by HOD'), ('HOD_APPROVED', 'HOD Approved'), ('RETURNED_BY_PRINCIPAL', 'Returned by Principal'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('LOCKED', 'Locked')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
