# Generated by Django 6.0.1 on 2026-01-21 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appraisal_hod_appraisal_principal_appraisal_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWD_BY_HOD', 'Reviewed by HOD'), ('RETURNED_BY_HOD', 'Returned by HOD'), ('HOD_APPROVED', 'HOD Approved'), ('REVIEWD_BY_PRINCIPAL', 'Reviewed by Principal'), ('RETURNED_BY_PRINCIPAL', 'Returned by Principal'), ('PRINCIPAL_APPROVED', 'Principal Approved'), ('LOCKED', 'Locked')], default='DRAFT', max_length=30),
        ),
    ]
