# Generated by Django 6.0.1 on 2026-01-21 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_hod_alter_appraisal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='from_state',
            field=models.CharField(default='SUBMITTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='to_state',
            field=models.CharField(default='SUBMITTED', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='appraisal',
            field=models.ForeignKey(db_column='appraisal_id', on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='core.appraisal'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='approved_by',
            field=models.ForeignKey(db_column='approved_by', on_delete=django.db.models.deletion.PROTECT, related_name='approvals_done', to=settings.AUTH_USER_MODEL),
        ),
    ]
