# Generated by Django 6.0.1 on 2026-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='is_hod_appraisal',
            field=models.BooleanField(default=False),
        ),
    ]
