# Generated by Django 6.0.1 on 2026-01-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appraisal_is_hod_appraisal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
