# Generated by Django 6.0.1 on 2026-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_facultyprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-logged_at']},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='role_snapshot',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_id_snapshot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='username_snapshot',
            field=models.CharField(default='UNKNOWN', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'entity_id'], name='audit_logs_entity_22e216_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id_snapshot'], name='audit_logs_user_id_a34a04_idx'),
        ),
    ]
