# Generated by Django 4.2.27 on 2026-01-31 09:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_user_address_user_assessment_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisalscore",
            name="acr_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=4
            ),
        ),
    ]
