# Generated by Django 4.2.27 on 2026-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appraisalscore_acr_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appraisal",
            name="form_type",
            field=models.CharField(
                choices=[("SPPU", "SPPU"), ("PBAS", "PBAS"), ("FACULTY", "FACULTY")],
                max_length=20,
            ),
        ),
    ]
