# Generated by Django 6.0.1 on 2026-02-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_appraisal_form_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalscore',
            name='verified_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
