# Generated by Django 5.2.11 on 2026-02-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_must_change_password'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['faculty', 'updated_at'], name='appraisals_faculty_89fe62_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['faculty', 'status', 'updated_at'], name='appraisals_faculty_24b79c_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['faculty', 'is_hod_appraisal', 'updated_at'], name='appraisals_faculty_14c138_idx'),
        ),
        migrations.AddIndex(
            model_name='appraisal',
            index=models.Index(fields=['status', 'updated_at'], name='appraisals_status_f617fb_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedpdf',
            index=models.Index(fields=['appraisal', 'generated_at'], name='generated_p_apprais_1fa531_idx'),
        ),
    ]
