
class States:
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    REVIEWED_BY_HOD = "REVIEWED_BY_HOD"
    HOD_APPROVED = "HOD_APPROVED"
    REVIEWED_BY_PRINCIPAL = "REVIEWED_BY_PRINCIPAL"
    PRINCIPAL_APPROVED = "PRINCIPAL_APPROVED"
    FINALIZED = "FINALIZED"



VALID_TRANSITIONS = {
    States.DRAFT: [States.SUBMITTED],
    States.SUBMITTED: [States.REVIEWED_BY_HOD, States.REVIEWED_BY_PRINCIPAL],
    States.REVIEWED_BY_HOD: [States.HOD_APPROVED, States.DRAFT],  # reject back to draft
    States.HOD_APPROVED: [States.REVIEWED_BY_PRINCIPAL],
    States.REVIEWED_BY_PRINCIPAL: [States.PRINCIPAL_APPROVED, States.DRAFT],
    States.PRINCIPAL_APPROVED: [States.FINALIZED]
}
